### ISSUE TITLE
use wordnet instead of PyDictionary

### ISSUE THREAD

**Issue by PandaWhoCodes** [geekpradd/PyDictionary#24]
This repo is really old and not maintained anymore. 
Use wordnet corpus in nltk - 
https://www.tutorialspoint.com/python/python_wordnet_interface.htm
Solves most of the issues on this repo.

**Comment by HanifCarroll** [comment]
> This repo is really old and not maintained anymore.
> Use wordnet corpus in nltk -
> https://www.tutorialspoint.com/python/python_wordnet_interface.htm
> Solves most of the issues on this repo.

Link is broken

**Comment by PandaWhoCodes** [comment]
https://pythonprogramming.net/wordnet-nltk-tutorial/

**Comment by geekpradd** [comment]
repo has been update and it's working now.
As of 2020 it's in active maintaining phase.
