### ISSUE TITLE
PyDictionary library is Dead !!!!

### ISSUE THREAD

**Issue by nikkkkhil** [geekpradd/PyDictionary#28]
RIP

**Comment by nikkkkhil** [comment]
PyDictionary is not **working anymore and not supported** alternatively, you can use **nltk wordnet** which is better than PyDictionary.
Getting started with wordnet 
```
import nltk
nlkt.download()
```
then install wordnet 
and you're ready to go 
example:
```
from nltk.corpus import wordnet 
syns = wordnet.synsets("pup")
print(syns[0].definition())
```
young of any of various canines such as a dog or wolf

follow this tutorial for more functions https://pythonprogramming.net/wordnet-nltk-tutorial/

**Comment by scott31878** [comment]
It looks like the release does not make the requests via a secured connection and does not follow the redirect.

**Comment by forgetso** [comment]
Wordnet is useless for antonyms and synonyms.

**Comment by geekpradd** [comment]
@above, I am sorry for not being able to update the plugin. School had taken up my time. I will be bringing the module back to a working state by the end of this month.
Thanks.
