### ISSUE TITLE
Error: The Following Error occured: list index out of range

### ISSUE THREAD

**Issue by KingWaffleIII** [geekpradd/PyDictionary#35]
For some reason, I keep getting this error (title) when I'm trying to use dictionary.meaning(). This isn't the case for most words like apple, book, etc. However, more complex words such as trimetric don't work and throw this error. I am generating words from another library and some words actually don't appear in the English dictionary at all so this may be the generator's problem.
If it helps, my generator library is NLTK (`python3 -m pip install nltk` then in a shell, do `import nltk` and then `nltk.download("words")`) (http://www.nltk.org/data.html).

The full code ran is:
`from nltk.corpus import words`
`from PyDictionary import PyDictionary`
`from random import choice`
`word_list = words.words()`
`word = choice(word_list).capitalize()`
`dictionary=PyDictionary()`
`dictionary.meaning(word)` -> Error: The Following Error occured: list index out of range 
`print(word)` -> "Judger"
`dictionary.meaning("Judger")` -> Error: The Following Error occured: list index out of range                                                         

![Screenshot from 2020-10-30 19-28-36](https://user-images.githubusercontent.com/43790097/97748977-38a3ef00-1ae6-11eb-8cfe-a7a5ec3f6f4c.png)
![Screenshot from 2020-10-30 19-29-11](https://user-images.githubusercontent.com/43790097/97748982-39d51c00-1ae6-11eb-9d77-be224e882411.png)

**Comment by jfabdo** [comment]
I'm getting this as well when I search a word it doesn't know. Here's an example:

```
>>> dictionary.definition("blarg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'PyDictionary' object has no attribute 'definition'
>>> dictionary.meaning("blarg")
Error: The Following Error occured: list index out of range
>>> dictionary.meaning("dad")
{'Noun': ['an informal term for a father; probably derived from baby talk']}
```

**Comment by jfabdo** [comment]
The issue is in `core.py`. Right at line 123, the dev needs to check if `lists` is empty if there are no definitions in there.

```
if not types or not lists:
                    return
```

should do the trick.

Good job making this, OP, but you need to improve your test coverage. "A word not in the dictionary" should be your first test case.

**Comment by KingWaffleIII** [comment]
I already tried a non-English word but it looks like I forgot to add it! Thanks for finding the error, I thought it had something to do with error checking but I didn't think of checking the code of the module!

**Comment by jamesdthor** [comment]
Also not sure on the source but it looks like the method is simply printing "Error" rather than throwing an error, normally this wouldn't be an issue but if I run the method in a try/except it doesn't break because no error is being thrown

**Comment by KingWaffleIII** [comment]
> Also not sure on the source but it looks like the method is simply printing "Error" rather than throwing an error, normally this wouldn't be an issue but if I run the method in a try/except it doesn't break because no error is being thrown

Yes, I don't believe it throws an error, rather it prints it. That could be very annoying in a program that is dependant on it. Thread's inactive now and there's no response so I'll close it.
