### ISSUE TITLE
Takes too long...

### ISSUE THREAD

**Issue by hg0428** [geekpradd/PyDictionary#41]
```python
def timeit(thing="welcome"):
   t=time.time()
   print(dictionary.meaning(thing))
   t=time.time()-t
   print("It took:", t)
   return t


dictionary=PyDictionary()
timeit()
```
> {'Noun': ['the state of being welcome', 'a greeting or reception'], 'Verb': ['accept gladly', 'bid welcome to; greet upon arrival', "receive someone, as into one's house"], 'Adjective': ['giving pleasure or satisfaction or received with pleasure or freely granted']}
> It took: 3.8481032848358154

That is 3.84 seconds! My search engine can not waste that much time for things as simple as that.

**Comment by geekpradd** [comment]
You probably need faster internet then. Sent from Android deviceOn Mar 4, 2021 16:39, hg0428 <notifications@github.com> wrote:
def timeit(thing="welcome"):
   t=time.time()
   print(dictionary.meaning(thing))
   t=time.time()-t
   print("It took:", t)
   return t


dictionary=PyDictionary()
timeit()

{'Noun': ['the state of being welcome', 'a greeting or reception'], 'Verb': ['accept gladly', 'bid welcome to; greet upon arrival', "receive someone, as into one's house"], 'Adjective': ['giving pleasure or satisfaction or received with pleasure or freely granted']}
It took: 3.8481032848358154

That is 3.84 seconds! My search engine can not waste that much time for things as simple as that.

**Comment by nmstoker** [comment]
Maybe you didn't mean it to, but this comes across as rather impolite and demanding, given this is provided freely for you to use.

Have you considered looking into why it is slow?

- maybe your outbound internet is slow for some reason (it sends queries to online sources to look up details)
- maybe your system is under resourced or hitting some performance block

You could look at caching the responses either in your search engine or add some code to PyDictionary so that everyone benefits from this.

**Comment by hg0428** [comment]
> Maybe you didn't mean it to, but this comes across as rather impolite and demanding, given this is provided freely for you to use.
> 
> Have you considered looking into why it is slow?
> 
> * maybe your outbound internet is slow for some reason (it sends queries to online sources to look up details)
> * maybe your system is under resourced or hitting some performance block
> 
> You could look at caching the responses either in your search engine or add some code to PyDictionary so that everyone benefits from this.

Sorry, I did not mean to sound rude. I would be glad to take a look at the code, but I am very limited on time. I used this module for version 1 of my search engine and for some reason it’s faster than version 2 that doesn’t even have dictionary yet.
Yes, I have considered those things.
